server:
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ems}
    username: ${DB_USERNAME:postgres} #Change it as per your local username
    password: ${DB_PASSWORD:admin}  #Change it as per your local password
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: /db.changelog/db.changelog-master.yaml
